### ISSUE TITLE
Add support for Python 3

### ISSUE THREAD

**Issue by cclauss** [vnpy/vnpy#818]
~#816~ attempted to provide support for Python 3 in a single pull request that touched 180 files!
That was too much change at one time so we need to take a more incremental approach:
- [x] Add [Travis Continuous Integration](https://travis-ci.org) to the project to automatically run [flake8](http://flake8.pycqa.org) tests (#819)
    - [x] #819 is merged
    - [ ] Travis CI service must be __turned on__.
- [x] Fix all flake8 failures on Python 2 (~#820~, ~#822~, ~#823~)
- [x] Run futurize on five files at a time and ensure they pass the tests on both Python 2 and Python 3 (#824)
- [x] Run futurize on the older examples (#825)
- [x] Repeat this small batch process until all of the codebase is compatible with both Python 2 and 3
    * https://github.com/vnpy/vnpy/issues/818#issuecomment-387305171

**Comment by cclauss** [comment]
@vnpy Any progress on getting these reviewed?

**Comment by viponedream** [comment]
可以写出怎么升级吗？整个过程。
同时做一份升级好的在你自己的GITHUB里面。

**Comment by mathprophet** [comment]
严重支持！需要py3版本！

**Comment by cclauss** [comment]
> Repeat this small batch process until all of the codebase is compatible with both Python 2 and 3
- [ ] turn on the Travis CI testing from  #819
- [ ] include the __six__ module in __setup.py__ #849 
- [ ] finish futurize __examples__ #848 
- [ ] futurize __beta__ #850 
- [ ] futurize __vnpy/data__
- [ ] futurize __vnpy/trader__
- [ ] futurize __vnpy/api__

**Comment by viponedream** [comment]
我觉得楼主不如一次性全部改好，
一块一块改更容易出差错。

**Comment by viponedream** [comment]
感谢楼主。
现在只是改python文件为兼容py3，但是一些api也要改成py3版本的吧？有的可能是2跟3不同的。不然虽说兼容3，但其实还是只能在2下面运行。

**Comment by cclauss** [comment]
Sequence of actions:
1. Get the whole codebase to work on Python 2 with no Python 3 syntax errors or undefined names
2. Get the whole codebase to work on both Python 2 and Python 3.

We are still on step 1 and will not start on step 2 until _after_ step 1 is completed.

**Comment by cclauss** [comment]
- [ ] #914 Runs __futurize --stage1 -w .__ on the entire repo.  It completes the stage1 process that was attempted in #816

**Comment by cclauss** [comment]
- [ ] #938 Runs __futurize --stage1 -w .__ on the entire repo to fix those changes made since #914. It is required because #870 is not yet done.  This PR should complete the __stage1__ process that was attempted in #816

**Comment by cclauss** [comment]
The next step in the conversion process is to run [__futurize --stage2 -w .__](http://python-future.org/automatic_conversion.html#step-2-working-py3-code-that-still-supports-py2).

It would be better/safer if people and/or [machines](https://github.com/vnpy/vnpy/issues/870) were testing the current _dev_ branch to ensure it is still working on Python 2.  Would it be possible to move the dev branch to master before we start satge2?

**Comment by vnpy** [comment]
Travis-ci is turned on now. Please let me know if there is any further work.

**Comment by cclauss** [comment]
The Python 3 fixes are in the __dev__ branch, not in the __master__ branch.

Can we have some users test the __dev__ branch on both Python 2 and on Python 3?
